# Generated by Django 4.2.2 on 2023-07-14 11:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereview',
            name='comment',
            field=ckeditor.fields.RichTextField(default='', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=ckeditor.fields.RichTextField(default='', verbose_name='comment'),
        ),
    ]
