# Generated by Django 4.2.2 on 2023-07-16 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_is_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
