# Generated by Django 4.2.2 on 2023-07-17 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_remove_product_is_favorite_product_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='product_is_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
